// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package memberModule

import (
	"github.com/google/wire"
	"golang/pkg/helpers"
	"golang/pkg/repos/implement"
	"golang/pkg/repos/interfaces"
	"golang/pkg/tokenModule"
)

// Injectors from wire.go:

func InitMemberController() *MemberController {
	db := helpers.NewSqlSession()
	memberRepo := implement.NewMemberRepo(db)
	tokenService := tokenModule.NewTokenService()
	memberService := NewMemberService(memberRepo, tokenService)
	memberController := NewMemberController(memberService)
	return memberController
}

// wire.go:

var MemberRepo = wire.NewSet(implement.NewMemberRepo, wire.Bind(new(interfaces.MemberRepo), new(*implement.MemberRepo)))
