// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package memberModule

import (
	"golang/pkg/helpers"
	"golang/pkg/repos"
)

// Injectors from wire.go:

func InitMemberController() *MemberController {
	db := helpers.NewSqlSession()
	memberRepo := repos.NewMemberRepo(db)
	memberService := NewMemberService(memberRepo)
	memberController := NewMemberController(memberService)
	return memberController
}
