name: Build and Test
on:
  push:
    branches:
      - unitTest
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Test 
      run: go test -v ./unitTest/test/...